pipeline {
    agent any
    environment {
        WORKSPACE = pwd() // 현재 워크스페이스 경로를 가져옴
    }
    stages {
        stage('GitHub Clone') {
            steps {
                // Git 클론 작업
                dir(WORKSPACE) {
                    git branch: 'develop', credentialsId: 'jenkins_token', url: 'https://lab.ssafy.com/s09-final/S09P31B107.git'
                }
            }
        }
        stage('Deployment') {
            steps {
                sshagent(credentials: ['ssh_key']) {
                    sh '''
                        echo "Connecting to remote server"
                        ssh -o StrictHostKeyChecking=no ubuntu@3.36.76.73

                        echo "Copying code to remote server"
                        scp -r /var/jenkins\_home/workspace/silapmyeon-FastAPI/FastAPI ubuntu@3.36.76.73:/home/ubuntu/fastapi

                        echo "Executing deploy script on remote server"
                        ssh -t ubuntu@3.36.76.73 ./deploy_fastapi.sh
                    '''
                }
            }
        }
    }
}
