pipeline {
    agent any
    stages {
        stage('github clone') {
            steps {
                git branch: 'develop', credentialsId: 'jenkins_token', url: 'https://lab.ssafy.com/s09-final/S09P31B107.git'
            }
        }
        stage('Deployment') {
            steps {
                sshagent(credentials: ['jenkins_token']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no ubuntu@ip-172-26-2-92
                        scp -r /jenkins/workspace/silapmyeon-FastAPI/FastAPI/ ubuntu@ip-172-26-2-92:/home/ubuntu/FastAPI/
                        ssh -t ubuntu@ip-172-26-2-92 ./deploy_fastapi.sh
                    '''
                }
            }
        }
    }
}