//자동배포 버전
pipeline {
    agent any

    stages {
        stage('Springboot build') {
            steps {
                dir('BE'){
                    sh '''
                    echo 'springboot build'
                    chmod +x gradlew 
                    ./gradlew clean build //스프링 부트 빌드, .jar파일 생성
                    '''
                }
            }
        }
        stage('Dockerimage build') {
            steps {
                dir('BE'){
                    sh '''
                    echo 'Dockerimage build'
                    docker build -t docker-springboot:0.0.1 .//도커 이미지파일 빌드
                    '''
                }
            }
        }
        stage('Deploy') {
            steps {
                dir('BE'){
                    sh '''
                    echo 'Deploy' //배포
												// 스프링 구동

										//최초 처음에 터미널에서 run한번 해줘야해 그 다음부터는 빌드할때마다 자동으로 멈추고 재실행 반복해줌 
										//docker run -d -p 8080:8080 --name springboot docker-springboot:0.0.1

	                docker stop springboot
                    docker rm springboot
                    docker run -d -p 8080:8080 --name springboot docker-springboot:0.0.1
                    '''
                }
            }
        }
    }
}